### ISSUE TITLE
Tracking issue for new Sonobuoy Plugins web page

### ISSUE THREAD

**Issue by jonasrosland** [vmware-tanzu/sonobuoy#1026]
This issue will track the work to get a new web page dedicated for Sonobuoy Plugins.

Wanted features:
- [x] Top level "Plugins" menu item
- [x] Card-like layout for each plugin
- [x] Pointers to documentation and other resources (blog post?) for the plugins
